[[article]]

id = "news"
title = "2025 August News Collection"
authors = ["Neruthes"]
authors_simple = "Neruthes"
date = "2025-08-31"
license = "CC BY-ND 4.0"
abstract = """
This article is a simple compilation of individual news articles published in 2025 August.
"""
